### ISSUE TITLE
Creating Buzz

### ISSUE THREAD

**Issue by Wiesusenurmitj** [compose-us-research/noqueue#2]
- [ ] Netzwerk nutzen 
- [ ] Netzwerk segmentieren: mit wem wollen wir Kontakt haben
- [ ] Daily Social Sharing
- [x] Draft 1 of Marketing Copy (Website
- [x] Draft 1 of Sales Copy (Pitch, 1 Pager und Anfragen Emailvorlagen)
- [x] Draft 1 of Readme Github Copy

**Comment by Wiesusenurmitj** [comment]
- [ ] Netzwerk nutzen

- [ ] Social Sharing

- [ ] Marketing Copy 

- [ ] Sales Copy

**Comment by Narigo** [comment]
Since this is in "Done" now, I'm closing this
