### ISSUE TITLE
Selectable timeslot can't be null

### ISSUE THREAD

**Issue by steffi501** [compose-us-research/noqueue#27]
1. Add a new store
2. Add timeslots 
3. Set the selectable timeslots
4. Don't touch the default value of the "from" time (0)
5. Save the timeslot

**What is the current bug behavior?**
No error message, nothing happens

**Possible fixes**
Idea: Maybe we should set the minimum value of the field to 15 minutes

**Comment by Narigo** [comment]
Doesn't this happen due to "nothing" in the max amount of people in shop?

**Comment by steffi501** [comment]
Yes, if you select nothing for the "max amount of people" it's the same error
