### ISSUE TITLE
Logo / Favicon

### ISSUE THREAD

**Issue by steffi501** [compose-us-research/noqueue#67]
**Description**
We need a Logo and a favicon that we can use for presentations etc etc. 

**Links/References**
Scribbles to discuss:
https://www.figma.com/file/STaHAZQn1B6mjhTFGpDcwb/No-Queue?node-id=344%3A29

Feel free to paste your ideas in Figma or in the comments below

**Comment by Narigo** [comment]
We've settled on this: 
![image](https://user-images.githubusercontent.com/1767865/87711855-28bb0600-c7a8-11ea-81f5-d2f3a7eead64.png)
