### ISSUE TITLE
New Shops Request

### ISSUE THREAD

**Issue by cowglow** [compose-us-research/noqueue#86]
**Description**
The creation of these new shops, in concern of the camping map integration

**Links/References**
- `camping-stein`
- `campingplatz-kupferschmiede`
- `seehaeusl-camping`
- `chiemsee-strandcamping`

**Tasks**

- [x] Create shops

**Additional Context**
Link used to integrate camping map

**Comment by Narigo** [comment]
Added campingplatz-moewenplatz as well.

They do not have any timeslots yet. Please add them through their `$reservationUrl/owner`

**Comment by Narigo** [comment]
This has been done already
