### ISSUE TITLE
Support day of the week in time slot

### ISSUE THREAD

**Issue by bergos** [compose-us-research/noqueue#9]
The time slot data model needs a day of the week column. The information of that column must be also processed in the API for the available tickets.

**Comment by Narigo** [comment]
Can we get rid of the `day` completely by looking at the `start` date object? Opening hours can be like Monday 17:00-02:00 (Tuesday). In the frontend I've used end date <= 24 hours beginning of the start slot, but I'm unsure if that's actually necessary.

Would it make sense to think of a shop being open 24/7 and have the invert of the selected times as "unavailable slots"?
